// <auto-generated />
using System;
using DnD35EDMTools.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnD35EDMTools.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260307230404_UpdatedItemCraftingDataType")]
    partial class UpdatedItemCraftingDataType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("CampaignDataSourceBookData", b =>
                {
                    b.Property<int>("AllowedSourcesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignSourceBooksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AllowedSourcesId", "CampaignSourceBooksId");

                    b.HasIndex("CampaignSourceBooksId");

                    b.ToTable("JoinTableCampaignSourceBooks", (string)null);
                });

            modelBuilder.Entity("ClassDataLanguageData", b =>
                {
                    b.Property<int>("AutomaticLanguagesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassDataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AutomaticLanguagesId", "ClassDataId");

                    b.HasIndex("ClassDataId");

                    b.ToTable("JoinTableClassAutomaticLanguages", (string)null);
                });

            modelBuilder.Entity("ClassDataLanguageData1", b =>
                {
                    b.Property<int>("BonusLanguagesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassData1Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("BonusLanguagesId", "ClassData1Id");

                    b.HasIndex("ClassData1Id");

                    b.ToTable("JoinTableClassBonusLanguages", (string)null);
                });

            modelBuilder.Entity("ClassDataSkillData", b =>
                {
                    b.Property<int>("ClassSkillsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassSkillsId", "ClassesId");

                    b.HasIndex("ClassesId");

                    b.ToTable("JoinTableClassSkills", (string)null);
                });

            modelBuilder.Entity("ColourDataRaceData", b =>
                {
                    b.Property<int>("EyeColoursId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceEyeColoursId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EyeColoursId", "RaceEyeColoursId");

                    b.HasIndex("RaceEyeColoursId");

                    b.ToTable("JoinTableRaceEyeColour", (string)null);
                });

            modelBuilder.Entity("ColourDataRaceData1", b =>
                {
                    b.Property<int>("HairColoursId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceHairColoursId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HairColoursId", "RaceHairColoursId");

                    b.HasIndex("RaceHairColoursId");

                    b.ToTable("JoinTableRaceHairColour", (string)null);
                });

            modelBuilder.Entity("ColourDataRaceData2", b =>
                {
                    b.Property<int>("RaceSkinColoursId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkinColoursId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RaceSkinColoursId", "SkinColoursId");

                    b.HasIndex("SkinColoursId");

                    b.ToTable("JoinTableRaceSkinColour", (string)null);
                });

            modelBuilder.Entity("DnD35EDMTools.Data.AlignmentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alignments");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DnD35EDMTools.Data.CampaignData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAvatarPoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowLuck")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowStartingEquipment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowStartingEquipmentCustomization")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowWealthAverage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowWealthRandom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRollWealth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HideTrainedOnlySkills")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HitPointRollingMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatRollingMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.CarryingCapacityData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeavyLoad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiftOffGround")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiftOverHead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LightLoad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediumLoad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PushOrDrag")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CarryingCapacity");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.CharacterData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CopperPieces")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Deity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eyes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldPieces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hair")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Morality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlatinumPieces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Race")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SilverPieces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.ClassData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("BaseAttackBonusPerLevel")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FortitudeSavePerLevel")
                        .HasColumnType("REAL");

                    b.Property<string>("HitDice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ReflexSavePerLevel")
                        .HasColumnType("REAL");

                    b.Property<int>("SkillPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartingGold")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WillSavePerLevel")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.CharacterInventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquippedSlot")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("CharacterId", "EquippedSlot")
                        .IsUnique()
                        .HasFilter("[EquippedSlot] IS NOT NULL AND [Location] = 'Equipped'");

                    b.ToTable("JoinTableCharacterInventory", (string)null);
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.CharacterLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HitPointsRolled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CharacterId", "Level")
                        .IsUnique();

                    b.ToTable("CharacterLevels");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.CharacterLevelSkillRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClassSkill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RanksPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("CharacterLevelId", "SkillId")
                        .IsUnique();

                    b.ToTable("JoinTableCharacterLevelSkillRanks", (string)null);
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.EquipmentPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceBook")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("EquipmentPacks");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.EquipmentPackItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentPackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentPackId");

                    b.HasIndex("ItemId");

                    b.ToTable("JoinTableEquipmentPackItems", (string)null);
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.ItemData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseGoldValue")
                        .HasColumnType("REAL");

                    b.Property<int>("BodySlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CraftCostXp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CraftDC")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CraftGoldCost")
                        .HasColumnType("REAL");

                    b.Property<string>("CraftRequiredFeats")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CraftSkillRequiredId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Enchantment")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemSubtype")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LootCategories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceBook")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CraftSkillRequiredId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.ItemProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyDefinitionId");

                    b.HasIndex("ItemId", "PropertyDefinitionId")
                        .IsUnique();

                    b.ToTable("JoinTableItemProperties", (string)null);
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.PropertyDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicableItemSubtypeIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicableItemTypeIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AppliedToSpecificSkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppliesTo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("EnchantmentCost")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GoldCostMultiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppliedToSpecificSkillId");

                    b.ToTable("PropertyDefinitions");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.SkillData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmourCheckPenaltyMultiplier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attribute")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustomizable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrainedOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sourcebook")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.ColourData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColourHexCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colours");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.DeityData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Setting")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deities");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.FeatsTraitsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnimalCompanionRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvatarPointCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FeatsTraitsDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RaceDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredAttributes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredRaces")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatsTraitsDataId");

                    b.HasIndex("RaceDataId");

                    b.ToTable("FeatsTraits");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.GenderData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.LanguageData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutomatic")
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sourcebook")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.MoralityData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Midpoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Morality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moralities");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.OrderData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Midpoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.RaceData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdulthoodAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharismaBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComplexDice")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConstitutionBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DexterityBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeatBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FemaleHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FemaleWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FortitudeBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeightDice")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("IntelligenceBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaleHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaleWeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaxAge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MiddleAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModerateDice")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("OldAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReflexBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SimpleDice")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillBonuses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillPointBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillPointsPerLevelBonus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("StrengthBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenerableAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeightDice")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("WillBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WisdomBonus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.SourceBookData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Implemented")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SourceBooks");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.SpellsSLAData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adapt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApostleofPeace")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Archivist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Artificer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assassin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Beguiler")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BelovedofValarian")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blackguard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blighter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChampionofGwynharwyn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cleric")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CloisteredCleric")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConcecratedHarrier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorruptAvenger")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeathDelver")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeathMaster")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Demonologist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscipleofThrym")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DivineCrusader")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DreadNecromancer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Druid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duskblade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EbonmarInfiltrator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmissaryofBarachiel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Factotum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fatemaker")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FavoredSoul")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiendofBlasphemy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GnomeArtificer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GpCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Healer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hexblade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hoardstealer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HolyLiberator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HunteroftheDead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JusticeofWealdandWoe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KenderNightstalker")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KnightoftheChalice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KnightoftheWeave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Manipulator")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialCost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mesmerist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonsterHunter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MortalHunter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mystic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NightLord")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OcularAdept")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Paladin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermanencyCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PiousTemplar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimeUnderdarkGuide")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RaceDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ranger")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SavingThrow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Scourge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShadeHunter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shair")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shugenja")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlayerofDomiel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sorcerer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpellDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpellLikeDc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellLikeLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpellName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpellResistance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpellSaveDc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpellSchool")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpellfireAdept")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Spellthief")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpiritShaman")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubSchool")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SublimeChord")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuelArcanamach")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TempleRaiderofOlidammara")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UrPriest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VassalofBahamut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vigilante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warblade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warlock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warmage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wizard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WuJen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpCost")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RaceDataId");

                    b.ToTable("SpellsSla");
                });

            modelBuilder.Entity("GenderDataRaceData", b =>
                {
                    b.Property<int>("GendersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceGendersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GendersId", "RaceGendersId");

                    b.HasIndex("RaceGendersId");

                    b.ToTable("JoinTableRaceGenders", (string)null);
                });

            modelBuilder.Entity("JoinTableAllowedAlignments", b =>
                {
                    b.Property<int>("AlignmentDataId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedAlignmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlignmentDataId", "AllowedAlignmentId");

                    b.HasIndex("AllowedAlignmentId");

                    b.ToTable("JoinTableAllowedAlignments");
                });

            modelBuilder.Entity("LanguageDataRaceData", b =>
                {
                    b.Property<int>("AutomaticLanguagesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceDataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AutomaticLanguagesId", "RaceDataId");

                    b.HasIndex("RaceDataId");

                    b.ToTable("JoinTableRaceAutomaticLanguages", (string)null);
                });

            modelBuilder.Entity("LanguageDataRaceData1", b =>
                {
                    b.Property<int>("BonusLanguagesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceData1Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("BonusLanguagesId", "RaceData1Id");

                    b.HasIndex("RaceData1Id");

                    b.ToTable("JoinTableRaceBonusLanguages", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CampaignDataSourceBookData", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.SourceBookData", null)
                        .WithMany()
                        .HasForeignKey("AllowedSourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.CampaignData", null)
                        .WithMany()
                        .HasForeignKey("CampaignSourceBooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassDataLanguageData", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.LanguageData", null)
                        .WithMany()
                        .HasForeignKey("AutomaticLanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.ClassData", null)
                        .WithMany()
                        .HasForeignKey("ClassDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassDataLanguageData1", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.LanguageData", null)
                        .WithMany()
                        .HasForeignKey("BonusLanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.ClassData", null)
                        .WithMany()
                        .HasForeignKey("ClassData1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassDataSkillData", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.Classes.SkillData", null)
                        .WithMany()
                        .HasForeignKey("ClassSkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.ClassData", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ColourDataRaceData", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.ColourData", null)
                        .WithMany()
                        .HasForeignKey("EyeColoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.RaceData", null)
                        .WithMany()
                        .HasForeignKey("RaceEyeColoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ColourDataRaceData1", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.ColourData", null)
                        .WithMany()
                        .HasForeignKey("HairColoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.RaceData", null)
                        .WithMany()
                        .HasForeignKey("RaceHairColoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ColourDataRaceData2", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.RaceData", null)
                        .WithMany()
                        .HasForeignKey("RaceSkinColoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.ColourData", null)
                        .WithMany()
                        .HasForeignKey("SkinColoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.CharacterInventoryItem", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.CharacterData", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.Classes.ItemData", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.CharacterLevel", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.CharacterData", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.ClassData", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.CharacterLevelSkillRank", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.Classes.CharacterLevel", "CharacterLevel")
                        .WithMany("SkillRanks")
                        .HasForeignKey("CharacterLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.Classes.SkillData", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CharacterLevel");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.EquipmentPackItem", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.Classes.EquipmentPack", "Pack")
                        .WithMany("Items")
                        .HasForeignKey("EquipmentPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.Classes.ItemData", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.ItemData", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.Classes.SkillData", "CraftSkillRequired")
                        .WithMany()
                        .HasForeignKey("CraftSkillRequiredId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CraftSkillRequired");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.ItemProperty", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.Classes.ItemData", "Item")
                        .WithMany("Properties")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.Classes.PropertyDefinition", "PropertyDefinition")
                        .WithMany()
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("PropertyDefinition");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.PropertyDefinition", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.Classes.SkillData", "AppliedToSpecificSkill")
                        .WithMany()
                        .HasForeignKey("AppliedToSpecificSkillId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppliedToSpecificSkill");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.FeatsTraitsData", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.FeatsTraitsData", null)
                        .WithMany("RequiredFeats")
                        .HasForeignKey("FeatsTraitsDataId");

                    b.HasOne("DnD35EDMTools.Data.RaceData", null)
                        .WithMany("RacialFeatureList")
                        .HasForeignKey("RaceDataId");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.SpellsSLAData", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.RaceData", null)
                        .WithMany("SpellLikeAbilities")
                        .HasForeignKey("RaceDataId");
                });

            modelBuilder.Entity("GenderDataRaceData", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.GenderData", null)
                        .WithMany()
                        .HasForeignKey("GendersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.RaceData", null)
                        .WithMany()
                        .HasForeignKey("RaceGendersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JoinTableAllowedAlignments", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.AlignmentData", null)
                        .WithMany()
                        .HasForeignKey("AlignmentDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.AlignmentData", null)
                        .WithMany()
                        .HasForeignKey("AllowedAlignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LanguageDataRaceData", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.LanguageData", null)
                        .WithMany()
                        .HasForeignKey("AutomaticLanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.RaceData", null)
                        .WithMany()
                        .HasForeignKey("RaceDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LanguageDataRaceData1", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.LanguageData", null)
                        .WithMany()
                        .HasForeignKey("BonusLanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.RaceData", null)
                        .WithMany()
                        .HasForeignKey("RaceData1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnD35EDMTools.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DnD35EDMTools.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.CharacterLevel", b =>
                {
                    b.Navigation("SkillRanks");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.EquipmentPack", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.Classes.ItemData", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.FeatsTraitsData", b =>
                {
                    b.Navigation("RequiredFeats");
                });

            modelBuilder.Entity("DnD35EDMTools.Data.RaceData", b =>
                {
                    b.Navigation("RacialFeatureList");

                    b.Navigation("SpellLikeAbilities");
                });
#pragma warning restore 612, 618
        }
    }
}
